yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech')
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls, name='admin'),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

from core.models import CreatedModel


User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        verbose_name='Group name',
        max_length=200,
        help_text='Name the group'
    )
    slug = models.SlugField(unique=True)
    description = models.TextField(
        verbose_name='description',
        help_text='What is this group about'
    )

    def __str__(self):
        return self.title


class Post(CreatedModel):
    text = models.TextField(
        verbose_name='Post text',
        help_text='Write your post here'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Post author'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        verbose_name='Group',
        help_text='Choose a group for the post'
    )
    image = models.ImageField(
        'Image',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date', '-id')
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'

    def __str__(self):
        return self.text[:15]


class Comment(CreatedModel):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Initial post'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Comment author'
    )
    text = models.TextField(
        verbose_name='Comment text',
        help_text='Write your comment here'
    )

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='User'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Post author'
    )

    class Meta:
        constraints = (models.UniqueConstraint(fields=('user_id',
                                                       'author_id'),
                                               name='unique_following'),)

    def __str__(self):
        return self.user

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {'text': 'Post text',
                  'group': 'Group',
                  'image': 'Image'}
        help_texts = {'text': 'Write your post here',
                      'group': 'Choose a group. Optional',
                      'image': 'Add an image'}


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {'text': 'Comment text'}
        help_texts = {'text': 'Please comment the post'}

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Comment, Follow, Group, Post, User


POST_NUMBER = 10


def do_pagination(request, posts):
    paginator = Paginator(posts, POST_NUMBER)
    page_number = request.GET.get('page')
    return paginator.get_page(page_number)


def index(request):
    posts = Post.objects.all()
    page_obj = do_pagination(request, posts)
    template = 'posts/index.html'
    context = {'page_obj': page_obj}
    return render(request, template, context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group).select_related('group').all()
    template = 'posts/group_list.html'
    page_obj = do_pagination(request, posts)
    context = {'group': group,
               'page_obj': page_obj, }
    return render(request, template, context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    page_obj = do_pagination(request, posts)
    template = 'posts/profile.html'
    following = (request.user.is_authenticated and Follow.objects.filter(
        user=request.user,
        author=author
    ).exists())

    context = {'page_obj': page_obj,
               'author': author,
               'following': following}
    return render(request, template, context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    comments = Comment.objects.filter(post_id=post_id)
    template = 'posts/post_detail.html'
    context = {'post': post,
               'form': form,
               'comments': comments}
    if form.is_valid():

        form_to_comment = form.save(commit=False)
        form_to_comment.post = post
        form_to_comment.save()

        return redirect('posts:post_detail', post_id=post_id)

    return render(request, template, context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None,
                    files=request.FILES or None)

    template = 'posts/create_post.html'
    context = {'form': form}
    if form.is_valid():

        form_to_post = form.save(commit=False)
        form_to_post.author = request.user
        form_to_post.save()

        return redirect('posts:profile', request.user.username)

    return render(request, template, context)


def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post.id)

    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=post)
    template = 'posts/create_post.html'
    context = {'form': form, 'post': post, 'is_edit': True}
    if form.is_valid():
        form.save()

        return redirect('posts:post_detail', post.id)

    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.filter(author__following__user=request.user)
    page_obj = do_pagination(request, posts)
    template = 'posts/follow.html'
    context = {'page_obj': page_obj}
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    '''Follow the author.'''
    if request.user.get_username() != username:
        Follow.objects.get_or_create(
            author=User.objects.get(username=username),
            user=request.user,
        )
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    '''Unfollow the author.'''
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
<!DOCTYPE html> 
<html lang="ru"> 
  {% load static %}
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="../img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="../img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="../img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="../img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href={% static 'css/bootstrap.min.css' %}>
    <title>Новый пост</title>
  </head>
  <body>	   
    <header>
      {%include 'includes/header.html'%} 
    </header>
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header"> 
                {% if is_edit %}
                  Редактировать запись
                {% else %}
                  Новый пост
                {% endif %}            
              </div>
              <div class="card-body">        
                <form method="post" enctype="multipart/form-data"> 
                  {% if is_edit %}
                    <action="{% url 'posts:post_edit' post.pk %}">
                  {% else %}
                    <action="{% url 'posts:post_create' %}">
                  {% endif %}
                {% csrf_token %}            
                  {{ form.as_p }}
                    <small id="id_group-help" class="form-text text-muted">
                      Группа, к которой будет относиться пост
                    </small>
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                        Сохранить
                      {% else %}
                        Добавить
                      {% endif %}               
                    </button> 
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
    <footer class="border-top text-center py-3">
      {%include 'includes/footer.html'%}
    </footer>
  </body>
</html>

yatube/templates/posts/follow.html
{% extends 'base.html' %}
<!DOCTYPE html> <!-- Используется html 5 версии -->
{% load thumbnail %}
{% load cache %}
<html lang="ru"> <!-- Язык сайта - русский -->
  <body>
    <main>
    {% block content %}
    <article>
      {% include 'includes/switcher.html' %}
    </article>
    
      <div class="container">        
        <h1>Последние посты по подписке</h1> 
        {% cache 20 div1 %}
        <div1>
        {% for post in page_obj %}
        <h5>Группа: {{ post.group }}</h5>
          <article>
            {% thumbnail post.image "900x400" crop="left" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
          </article>  
          <article>
            {% include 'includes/article.html' %}
          </article>
          {% if post.group %}
            <a href={% url 'posts:group' post.group.slug %}>все записи группы</a>
          {% endif %}

          <p>
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %} 
      </div1>
      {% endcache %} 
        <paginator>
          {% include 'posts/includes/paginator.html' %}
        </paginator>
      </div>
    
    {% endblock %}
    </main>
    <!-- Использованы классы бутстрапа: -->
    <!-- border-top: создаёт тонкую линию сверху блока -->
    <!-- text-center: выравнивает текстовые блоки внутри блока по центру -->
    <!-- py-3: контент внутри размещается с отступом сверху и снизу -->         
  </body>
</html>

yatube/templates/posts/group_list.html
{%extends 'base.html' %}
<!DOCTYPE html> <!-- Используется html 5 версии -->
{% load thumbnail %}
<html lang="ru"> <!-- Язык сайта - русский -->
  <body>
    <main>
      {% block content %}
      <div class="container py-5">
        <h1>{{ group.title }}</h1>
          <p>{{ group.description }}</p>
          <h3>Всего постов в группе: {{ group.posts.count }}</h3>
        {% for post in page_obj %}
          <article>
            {% include 'includes/article.html' %}
            {% include 'posts/includes/pictures.html' %}
          </article>
        {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        <paginator>
          {% include 'posts/includes/paginator.html' %}
        </paginator>
        </div>
        {% endblock %}
    </main>
  </body>
</html>

yatube/templates/posts/index.html
{% extends 'base.html' %}
<!DOCTYPE html> <!-- Используется html 5 версии -->
{% load thumbnail %}
{% load cache %}
<html lang="ru"> <!-- Язык сайта - русский -->
  <body>
    <main>
    {% block content %}
    <article>
      {% include 'includes/switcher.html' %}
    </article>
    
      <div class="container">        
        <h1>Последние обновления на сайте</h1>
        {% cache 20 div2 %}
        <div2>
        {% for post in page_obj %}
        <h5>Группа: {{ post.group }}</h5>
          <article>
            {% thumbnail post.image "900x400" crop="left" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
          </article>  
          <article>
            {% include 'includes/article.html' %}
          </article>
            {% if post.group %}
              <a href={% url 'posts:group' post.group.slug %}>все записи группы</a>
            {% endif %}
             <p>
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
      </div2>
      {% endcache %}  
        <paginator>
          {% include 'posts/includes/paginator.html' %}
        </paginator>
      </div>
    
    {% endblock %}
    </main>
    <!-- Использованы классы бутстрапа: -->
    <!-- border-top: создаёт тонкую линию сверху блока -->
    <!-- text-center: выравнивает текстовые блоки внутри блока по центру -->
    <!-- py-3: контент внутри размещается с отступом сверху и снизу -->         
  </body>
</html>

yatube/templates/posts/post_detail.html
<!DOCTYPE html>
<html lang="ru">
  {% load static %}
  {% load thumbnail %}
  <head>    
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href={% static 'img/fav/fav.ico' %} type="image">
    <link rel="apple-touch-icon" sizes="180x180"
      href={% static 'img/fav/apple-touch-icon.png' %}>
    <link rel="icon" type="image/png" sizes="32x32" 
      href={% static 'img/fav/favicon-32x32.png' %}>
    <link rel="icon" type="image/png" sizes="16x16" 
      href={% static 'img/fav/favicon-16x16.png' %}>
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href={% static 'css/bootstrap.min.css' %}>
    <title>Пост {{ post.text|truncatechars:30 }}</title>
  </head>
  <body>
    <header>
      {%include 'includes/header.html'%}  
    </header> 
    <main>
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }} 
            </li>
            <!-- если у поста есть группа -->   
            <li class="list-group-item">
              {% if post.group %}
                Группа: {{ post.group }}
              <a href={% url 'posts:group' post.group.slug %}>
                все записи группы
              </a>
              {% endif %}
            </li>
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ post.author.posts.count }}</span>
            </li>
            <li class="list-group-item">
              <a href={% url 'posts:profile' post.author.username %}>
                все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-8">
          <p>
            <article>
              {% thumbnail post.image "900x400" crop="left" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}">
              {% endthumbnail %}
              Текст поста:<br>
              <textarea name="text" style="width: 900px" rows="5" class="form-control" required id="id_text">
              {{ post.text }}
              </textarea> 
            </article>
            </p>
          {% if user == post.author %}
            <a class="btn btn-primary" href={% url 'posts:post_edit' post.pk %}>
              редактировать запись
            </a> 
          {% endif%}
          <p>
            {%include 'posts/includes/comment.html'%}
          </p>
        </article>
      </div> 
    </main>
    <footer class="border-top text-center py-3">
      {%include 'includes/footer.html'%}
    </footer>
  </body>
</html>

yatube/templates/posts/profile.html
<!DOCTYPE html>
<html lang="ru"> 
  {% load static %}
  {% load thumbnail %}
  <head>    
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href={% static 'img/fav/fav.ico' %} type="image">
    <link rel="apple-touch-icon" sizes="180x180"
      href={% static 'img/fav/apple-touch-icon.png' %}>
    <link rel="icon" type="image/png" sizes="32x32" 
      href={% static 'img/fav/favicon-32x32.png' %}>
    <link rel="icon" type="image/png" sizes="16x16" 
      href={% static 'img/fav/favicon-16x16.png' %}>
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href={% static 'css/bootstrap.min.css' %}>
    <title>Профайл пользователя {{ author.get_full_name }}</title>
  </head>
  <body>
    <header>
      {%include 'includes/header.html'%}  
    </header> 
      <main>
      <div class="container py-5">        
        <h1>Все посты пользователя {{ author.get_full_name }} </h1>
        <h3>Всего постов: {{ author.posts.count }}</h3>
          {% if user.is_authenticated %}
            {% if author.username != request.user.username %}
              {% if following %}
                <a
                  class="btn btn-lg btn-light"
                  href="{% url 'posts:profile_unfollow' author.username %}" role="button"
                >
                  Отписаться
                </a>
              {% else %}
                <a
                  class="btn btn-lg btn-primary"
                  href="{% url 'posts:profile_follow' author.username %}" role="button"
                >
                  Подписаться
                </a>
              {% endif %}
            {% endif %}
          {% endif %}
        {% for post in page_obj %}
        <article>
          {% include 'includes/article.html' %}
          {% include 'posts/includes/pictures.html' %}
          <a href={% url 'posts:post_detail' post.id %}>подробная информация </a>
        </article>       
        {% if not forloop.last %}<hr>{% endif %}
        {% endfor %} 
        <a href="">все записи группы</a>
        <paginator>
          {% include 'posts/includes/paginator.html' %}
        </paginator>
        <hr>
        <!-- Остальные посты. после последнего нет черты -->
        <!-- Здесь подключён паджинатор -->  
      </div>
      </main>
    <footer class="border-top text-center py-3">
      {%include 'includes/footer.html'%}
    </footer>
  </body>
</html>